name: Build

on: [push]

jobs:

  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y -o Acquire::Retries=50 \
            autoconf-archive gettext libcmocka-dev
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build
        run: |
          ./autogen.sh
          ./configure
          make
          make check
      - name: Upload failure artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: linux-failure
          path: |
            .
            !src/edk2
      - name: Distribution
        run: |
          make distcheck
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: efikit-*.tar.gz
          if-no-files-found: error

  mingw:
    name: MinGW
    needs: linux
    runs-on: ubuntu-latest
    container: fedora
    steps:
      - name: Install packages
        run: |
          dnf install -y make libtool gettext-devel \
            mingw64-gcc mingw64-win-iconv mingw64-glib2 mingw64-cmocka \
            wine-common wine-systemd
      - name: Configure environment
        run: |
          # Initialise ~/.wine directory
          mkdir ~/.wine
          wineboot -i
          wineserver -w
          # Patch ~/.wine/system.reg to include path to MinGW libraries
          MINGWPATH=$(winepath -w /usr/x86_64-w64-mingw32/sys-root/mingw/bin)
          QMINGWPATH=$(printf '%q' ${MINGWPATH})
          QQMINGWPATH=$(printf '%q' ${QMINGWPATH})
          sed -i "s/^\(\"PATH\"=.*\)\"$/\1;${QQMINGWPATH}\"/" \
            ~/.wine/system.reg
      - name: Download
        uses: actions/download-artifact@v2
        with:
          name: dist
      - name: Unpack
        run: |
          tar --strip-components=1 -xvf efikit-*.tar.gz
      - name: Build
        run: |
          ./configure --build= --host=x86_64-w64-mingw32
          make
          wine ./src/efidevpath.exe -h
      - name: Upload failure artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: mingw-failure
          path: .

  windows:
    name: Windows
    needs: linux
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Install packages
        uses: msys2/setup-msys2@v2
        with:
          install: >
            base-devel
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-glib2
            mingw-w64-x86_64-cmocka
      - name: Download
        uses: actions/download-artifact@v2
        with:
          name: dist
      - name: Unpack
        run: |
          tar --strip-components=1 -xvf efikit-*.tar.gz
      - name: Build
        run: |
          ./configure
          make
          make check
      - name: Upload failure artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: windows-failure
          path: .
