name: Build

on: [push]

jobs:

  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y -o Acquire::Retries=50 \
            gettext
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build
        run: |
          ./autogen.sh
          ./configure
          make
          make check
      - name: Upload failure artifacts
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: failed
          path: .
      - name: Distribution
        run: |
          make distcheck

  windows:
    name: Windows
    runs-on: ubuntu-latest
    container: fedora
    steps:
      - name: Install packages
        run: |
          dnf install -y git make libtool gettext-devel \
            mingw64-gcc mingw64-win-iconv mingw64-glib2 wine-core
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build
        run: |
          ./autogen.sh
          ./configure --build= --host=x86_64-w64-mingw32
          make
          make check
      - name: Upload failure artifacts
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: failed
          path: .
