name: Build

on: [push]

jobs:

  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y -o Acquire::Retries=50 \
            gettext libcmocka-dev
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build
        run: |
          ./autogen.sh
          ./configure
          make
          make check
      - name: Upload failure artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: failed
          path: |
            .
            !src/edk2
      - name: Distribution
        run: |
          make distcheck

  mingw:
    name: MinGW
    runs-on: ubuntu-latest
    container: fedora
    steps:
      - name: Install packages
        run: |
          dnf install -y git make libtool gettext-devel \
            mingw64-gcc mingw64-win-iconv mingw64-glib2 mingw64-cmocka \
            wine-common wine-systemd
      - name: Configure environment
        run: |
          # Initialise ~/.wine directory
          mkdir ~/.wine
          wineboot -i
          wineserver -w
          # Patch ~/.wine/system.reg to include path to MinGW libraries
          MINGWPATH=$(winepath -w /usr/x86_64-w64-mingw32/sys-root/mingw/bin)
          QMINGWPATH=$(printf '%q' ${MINGWPATH})
          QQMINGWPATH=$(printf '%q' ${QMINGWPATH})
          sed -i "s/^\(\"PATH\"=.*\)\"$/\1;${QQMINGWPATH}\"/" \
            ~/.wine/system.reg
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build
        run: |
          ./autogen.sh
          ./configure --build= --host=x86_64-w64-mingw32
          make
          wine ./src/efidevpath.exe -h
      - name: Upload failure artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: failed
          path: |
            .
            !src/edk2
